<?php

namespace AppBundle\Repository;

/**
 * athleteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class athleteRepository extends \Doctrine\ORM\EntityRepository
{
}
