<?php

namespace AppBundle\Repository;

/**
 * resultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class resultRepository extends \Doctrine\ORM\EntityRepository
{
}
